services:
  api:
    image: debian:bookworm-slim
    command: ["/app/salah"]
    networks:
      - server
    volumes:
      - ./target/size/salah-server:/app/salah:ro
  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - server
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

networks:
  server:
    driver: bridge