FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:latest

ENV PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig

RUN dpkg --add-architecture armhf
RUN apt update && apt upgrade -y
RUN apt install -y \
	libasound2-dev:armhf \
	libasound2:armhf \
	libssl-dev:armhf \
	gcc-arm-linux-gnueabihf
