FROM rust:slim-bullseye

WORKDIR /server

COPY Cargo.lock .
COPY server/Cargo.toml Cargo.toml
RUN mkdir src && touch src/lib.rs 
RUN cargo fetch

COPY server/src/lib.rs src/lib.rs
COPY server/src/server.rs src/server.rs
RUN cargo check --release
RUN cargo build --release

COPY server/src/main.rs src/main.rs

CMD ["cargo", "run", "--release"]