name: Build Adhan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2 libasound2-dev
          version: 1.0
      - name: Prepare cargo cache
        uses: actions/cache@v4
        with:
          key: cargo-cache
          path: /home/runner/.cargo
      - name: Prepare target cache
        uses: actions/cache@v4
        with:
          key: target-cache
          path: target
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile size
