name: Build Adhan (ARM64)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare image cache
        uses: actions/cache@v4
        with:
          key: image-cache-aarch64-unknown-linux-gnu
          path: /tmp/.image-cache-aarch64-unknown-linux-gnu
      - name: Prepare cargo cache
        uses: actions/cache@v4
        with:
          key: cargo-cache-aarch64-unknown-linux-gnu
          path: /home/runner/.cargo
      - name: Prepare target cache
        uses: actions/cache@v4
        with:
          key: target-cache-aarch64-unknown-linux-gnu
          path: target
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Set build toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - name: Setup image builder
        id: image-builder
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.image-builder.outputs.name }}
          cache-from: "type=local,src=/tmp/.image-cache-aarch64-unknown-linux-gnu"
          cache-to: "type=local,dest=/tmp/.image-cache-aarch64-unknown-linux-gnu"
          file: ARM64.Dockerfile
          tags: |
            adhan-arm64:latest
            localhost/adhan-arm64:latest
            docker.io/library/adhan-arm64:latest
          load: true
      - name: Build binary
        run: cross build --target aarch64-unknown-linux-gnu --profile size
