name: Build Adhan (ARM)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arm-arch: [armv7-unknown-linux-gnueabihf, aarch64-unknown-linux-gnu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare cargo cache
        uses: actions/cache@v4
        with:
          key: cargo-cache-${{matrix.arm-arch}}
          path: /home/runner/.cargo
      - name: Prepare target cache
        uses: actions/cache@v4
        with:
          key: target-cache-${{matrix.arm-arch}}
          path: target
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: Set build toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arm-arch }}
          override: true
      - name: Build binary
        run: cross build --target ${{ matrix.arm-arch }} --profile size
