name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2 libasound2-dev
          version: 1.0
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2.7.3
      - name: Build binary
        run: cargo build --profile performance --verbose
      - name: Run tests
        run: cargo test --verbose
